### ISSUE TITLE
Internal server oopsie, please grab a programmer!

### ISSUE THREAD

**Issue by galalaly** [ah450/evaluator#5]
1. The website remembered my login.
2. Homepage gave this error : Internal server oopsie, please grab a programmer!
3. Clicked Courses from the menu, chose a course.
4. Got the same error again: Internal server oopsie, please grab a programmer!
5. I logged out and I can not login now.

**Comment by amrdraz** [comment]
We had a security bug so we invalidated everyone's login.

After logging out you may have not been using your correct password.

Simply use forgot my password to reset your password.

If it turns out you account is not activated request an activation email.

After resetting your password everything should turn out fine
